name: Create Glue Job and Trigger

on:
  workflow_dispatch:
  push:
    branches:
      - glue

jobs:
  create-and-trigger-glue-job:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1  # Replace with your desired AWS region

     
      - name: Create Glue Job
        id: create-glue-job
        run: |
          # Get the ARN of the IAM role
          ROLE_ARN=$(aws iam get-role --role-name AWS-Glue --query 'Role.Arn' --output text)

          # Generate timestamp
          TIMESTAMP=$(date +"%Y%m%d%H%M%S")

          # Concatenate timestamp with job name
          JOB_NAME="Data-glue-job-${TIMESTAMP}"

          # Create Glue job referencing the GitHub location of the script
          aws glue create-job --name "${JOB_NAME}"  \
                        --role "$ROLE_ARN" \
                        --command 'Name=glueetl,ScriptLocation=https://raw.githubusercontent.com/Devopsawsr/PHOTOSEC/glue/.github/scripts/trigger_glue_job.py' \
                        --default-arguments '{"--job-language": "python"}'
          echo "::set-output name=job-name::${JOB_NAME}"

      - name: Install dependencies
        run: pip install boto3
      
      - name: Run Python script
        run: python .github/scripts/trigger_glue_job.py $GITHUB_JOB_NAME
        env:
          GITHUB_JOB_NAME: ${{ steps.create-glue-job.outputs.job-name }}
