name: Notify New Relic of Workflow Status

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  hello-world:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repository
        uses: actions/checkout@v2

      - name: Run Hello World
        run: echo "hello world"

      - name: Notify New Relic of Success
        if: success()
        env:
          NEW_RELIC_INSERT_KEY: ${{ secrets.NEW_RELIC_INSERT_KEY }}
          NEW_RELIC_ACCOUNT_ID: ${{ secrets.NEW_RELIC_ACCOUNT_ID }}
        run: |
          curl -X POST -H "Content-Type: application/json" \
          -H "X-Insert-Key:${{ env.NEW_RELIC_INSERT_KEY }}" \
          -d \
          '{
            "eventType": "WorkflowStatus",
            "workflow": "${{ github.workflow }}",
            "status": "success",
            "repository": "${{ github.repository }}",
            "commit": "${{ github.sha }}",
            "actor": "${{ github.actor }}"
          }' \
          https://insights-collector.newrelic.com/v1/accounts/${{ env.NEW_RELIC_ACCOUNT_ID }}/events

      - name: Notify New Relic of Failure
        if: failure()
        env:
          NEW_RELIC_INSERT_KEY: ${{ secrets.NEW_RELIC_INSERT_KEY }}
          NEW_RELIC_ACCOUNT_ID: ${{ secrets.NEW_RELIC_ACCOUNT_ID }}
        run: |
          curl -X POST -H "Content-Type: application/json" \
          -H "X-Insert-Key:${{ env.NEW_RELIC_INSERT_KEY }}" \
          -d \
          '{
            "eventType": "WorkflowStatus",
            "workflow": "${{ github.workflow }}",
            "status": "failure",
            "repository": "${{ github.repository }}",
            "commit": "${{ github.sha }}",
            "actor": "${{ github.actor }}"
          }' \
          https://insights-collector.newrelic.com/v1/accounts/${{ env.NEW_RELIC_ACCOUNT_ID }}/events
