name: Notify New Relic of Deployment
 
on:
  push:
    branches:
      - main
 
jobs:
  notify-newrelic:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository
        uses: actions/checkout@v2
 
      - name: Notify New Relic
        env:
          NEW_RELIC_API_KEY: ${{ secrets.NEW_RELIC_API_KEY }}
          NEW_RELIC_APP_ID: ${{ secrets.NEW_RELIC_APP_ID }}
        run: |
          curl -X POST "https://api.newrelic.com/v2/applications/${{ env.NEW_RELIC_APP_ID }}/deployments.json" \
          -H "X-Api-Key:${{ env.NEW_RELIC_API_KEY }}" \
          -i \
          -H "Content-Type: application/json" \
          -d \
          '{
            "deployment": {
              "revision": "${{ github.sha }}",
              "description": "${{ github.event.head_commit.message }}",
              "user": "${{ github.actor }}"
            }
          }'
